entities:
  #CORE свойства требований
  seaf.change.requirements:
    title: Требования
    objects:
      requirement:
        route: "/"
        title: Требование
    schema:
      $defs:
        seaf.change.requirements.def:
          type: object
          #          patternProperties:
          #            "^[a-zA-Z][a-zA-Z0-9_-]*(\\.[a-zA-Z0-9][a-zA-Z0-9_-]*)*$": # предыдущий вариант "^[a-z0-9_\\$][a-z0-9_\\$]*(\\.[a-z0-9_\\$][a-z0-9_\\$]*)*$":
          properties:
            title:
              title: Название требования
              type: string
            type:
              type: string
              enum:
                - business
                - functional
                - non-functional
            statement:
              title: Формулировка (содержание) требования
              type: string
            functionality:
              title: Функции обеспечивающие требование
              type: array
              items:
                $ref: "#/$rels/aspects.aspect"
            description:
              title: Подробное описание требования
              type: string
            drivers: #массив строк и необязательное свойство
              title: Драйвер требования
              type: array
              items:
                type: string
            exceptions_acceptance_level:
              title: Уровень согласования отклонений
              type: string
            stakeholders:
              title: Заказчики требования
              type: array
              items:
                type: string
            tags:
              title: Тег требования
              type: array
              items:
                type: string
            comments:
              title: Комментарии, пояснения
              type: string
            verifications:
              title: Критерии выполнения
              type: object
              patternProperties:
                "^[a-z0-9_\\$][a-z0-9_\\$]*(\\.[a-z0-9_\\$][a-z0-9_\\$]*)*$":
                  type: object
                  properties:
                    title:
                      type: string
                      title: Название критерия
                    condition:
                      type: string
                      title: Условие выполнения критерия проверки
                  required:
                    - title
                    - condition
#          required:
#            - title # не является необходимым. Если не заполнено, то требование не выводится в меню, но должно выводиться, например, в таблицу. Для требований стандартов не заполняется (требований много, в меню они не нужны
#            - type #решили сделать пока необязательным, так как необходимо переработать классификатор требований, и в требованиях стандартов отнесение к типу требования пока отсутствует
#            - description #необязательное ввиду того что при вводе требований стандаров основной текст вводится в statement и как правило, нет дополнительного описания или комментариев. Обязательнось избыточна
#            - verifications #необязательное ввиду того что при вводе требований, как правило, нет критериев. В требованиях стандартов часто нет критериев. Обязательнось избыточна
      patternProperties:
        "^[a-zA-Z][a-zA-Z0-9_-]*(\\.[a-zA-Z0-9][a-zA-Z0-9_-]*)*$": # предыдущий вариант"^[a-z0-9_\\$][a-z0-9_\\$]*(\\.[a-z0-9_\\$][a-z0-9_\\$]*)*$": # Как управлять ЖЦ требований. Одно требование в двух версиях стандарта - должны быть разные требования с различными идентификаторами
          type: object
          $ref: "#/$defs/seaf.change.requirements.def"
    menu: >
      (
        $append(
          [{
            "link": "/entities/seaf.change.requirements/tree", 
            "location": "Изменения/Требования" 
          }],
          $seaf_menu_location_by_id(
              $."seaf.change.requirements",
              "",
              "Изменения/Требования/",
              function($location, $item, $itemId, $collection){{
                  "location": $location,
                  "link": "/entities/seaf.change.requirements/blank?seaf-req-id=" & $itemId
              }}
          )
        );
      )
