# ADR (Architecture Decision Record)
# Основано на https://github.com/joelparkerhenderson/architecture-decision-record
entities:
  seaf.change.adr:
    title: Architecture Decision Record
    schema:
      $defs:
        seaf.change.adr.issue:
          type: string
          title: Описание проблемы
          description: >
            Опишите проблему архитектурного проектирования, которую вы решаете,
            не оставляя вопросов о том, почему вы решаете эту проблему сейчас.
            Следуя минималистскому подходу, рассматривайте и документируйте только
            те проблемы, которые требуют решения на различных этапах жизненного цикла.
        seaf.change.adr.decision:
          type: string
          title: Решение
          description: >
            Четко определите архитектурное решение.
        seaf.change.adr.affects.area:
          title: Область эффекта
          type: string
          enum:
            - people      # Люди
            - money       # Деньги
            - resources   # Ресурсы
            - time        # Время
            - business    # Бизнес
            - technology  # Технологии
            - other       # Прочее
        seaf.change.adr.affects.vector:
          title: Область эффекта
          type: string
          enum:
            - negative    # Негативное влияние
            - positive    # Позитивное влияние
            - unknown     # Неизвестно
        seaf.change.adr.context.item:
          title: Характеристика контекста
          type: object
          properties:
            area:
              $ref: "#/$defs/seaf.change.adr.affects.area"
            vector:
              $ref: "#/$defs/seaf.change.adr.affects.vector"
            content:
              title: Описание характеристики
              type: string
              description: >
                Четко опишите характеристику контекста
          required:
            - area
            - vector
            - content
        seaf.change.adr.context:
          title: Предпосылки принятия решения
          description: >
            Укажите все важные сведения влияющие на принятие решения
          type: array
          minItems: 1
          items:
            $ref: "#/$defs/seaf.change.adr.context.item"
        seaf.change.adr.consequences.item:
          title: Характеристика последствий
          type: object
          properties:
            area:
              $ref: "#/$defs/seaf.change.adr.affects.area"
            vector:
              $ref: "#/$defs/seaf.change.adr.affects.vector"
            content:
              title: Описание характеристики
              type: string
              description: >
                Четко опишите последствия принятого решения
          required:
            - area
            - vector
            - content
        seaf.change.adr.consequences:
          title: Последствия
          description: >
            Укажите все важные последствия принятого архитектурного решения
          type: array
          minItems: 1
          items:
            $ref: "#/$defs/seaf.change.adr.consequences.item"
        seaf.change.adr.requirements.item:
          title: Требование
          description: >
            Укажите требование, которое удовлетворяет решение
          $ref: "#/$rels/seaf.change.requirements.requirement"
        seaf.change.adr.requirements:
          title: Требования
          description: >
            Перечислите требование, которые должно удовлетворить архитектурное решение
          type: array
          minItems: 1
          items:
            $ref: "#/$defs/seaf.change.adr.requirements.item"
        seaf.change.adr.deciders.item:
          title: Принимающий решение
          type: string
        seaf.change.adr.deciders:
          title: Кто принял решение
          description: >
            Укажите всех, кто принимал архитектурное решение.
          type: array
          minItems: 1
          items:
            $ref: "#/$defs/seaf.change.adr.deciders.item"
        seaf.change.adr.dependencies.item:
          title: Зависимость от другого решения
          $ref: "#/$rels/seaf.change.adr.adr"
        seaf.change.adr.dependencies:
          title: Зависимости от других решений
          description: >
            Укажите от каких решений зависит данное
          type: array
          minItems: 1
          items:
            $ref: "#/$defs/seaf.change.adr.dependencies.item"
        seaf.change.adr:
          type: object
          properties:
            title:
              type: string
              title: Название
            moment:
              type: string
              title: Дата создания
              pattern: ^[0-9]{4}\-[0-9]{2}\-[0-9]{2}$
            issue:
              $ref: "#/$defs/seaf.change.adr.issue"
            deciders:
              $ref: "#/$defs/seaf.change.adr.deciders"
            decision:
              $ref: "#/$defs/seaf.change.adr.decision"
            context:
              $ref: "#/$defs/seaf.change.adr.context"
            consequences:
              $ref: "#/$defs/seaf.change.adr.consequences"
            requirements:
              $ref: "#/$defs/seaf.change.adr.requirements"
            dependencies:
              $ref: "#/$defs/seaf.change.adr.dependencies"
          required:
            - title
            - moment
            - issue
            - decision
            - status
            - context
            - context
            - consequences
      type: object
      patternProperties:
        "^[a-z0-9_\\$][a-z0-9_\\$]*(\\.[a-z0-9_\\$][a-z0-9_\\$]*)*$":
          $ref: "#/$defs/seaf.change.adr"
    objects:
      adr:
        route: "/"
        title: ADR
    menu: >
      (       
          $append(
              [{
                  "location": "Изменения/ADR",
                  "link": "/entities/seaf.change.adr/list"
              }],
              $seaf_menu_location_by_id(
                    $."seaf.change.adr",
                    "",
                    "Изменения/ADR/",
                    function($location, $item, $itemId, $collection){{
                        "location": $location,
                        "link": "/entities/seaf.change.adr/blank?seaf-adr-id=" & $itemId
                    }}
            )
        );
      )