entities:
  seaf.ta.services.environment:
    title: Environment
    objects:
      environment:
        route: "/"
        title: Имя окружения
    schema:
      type: object
      patternProperties:
        "^[a-zA-Z0-9_\\.]*$":
          $ref: "#/$defs/seaf.ta.services.base.entity"
          properties:
            environment_id:
              title: Environment ID
              type: string
          required:
            - environment_id

  seaf.ta.services.stand:
    title: Techical Stand
    objects:
      stand:
        route: "/"
        title: Имя стенда внутри окружения
    schema:
      type: object
      patternProperties:
        "^[a-zA-Z0-9_\\.]*$":
          $ref: "#/$defs/seaf.ta.services.base.entity"
          properties:
            stand_name:
              title: Stand ID
              type: string
            environment_id:
              title: В какое окружение входит стенд
              $ref: "#/$rels/seaf.ta.services.environment.environment"
          required:
            - stand_name
            - environment_id
